#!/usr/bin/env python

import sys
import requests
import json
try:
    from urllib import quote  # Python 2.X
except ImportError:
    from urllib.parse import quote  # Python 3+

"""
NOTE: This API endpoint is extremely experimental and likely to break. 
This code is just scaffolding. It's literally four lines. 
Plz file bugs to https://github.com/GreyNoise-Intelligence/gnql


TODO:
- Incorporate into pygreynoise
- COLORS / ANIMATIONS
- Field selection
- Clean up grammar
- Make forward slashes less of a pain in the ass
- Multiple output options (JSON, CSV, Plaintext, XML)
- Pagination
"""

# Insert your GreyNoise Enterprise / Research Tools key here
GREYNOISE_API_KEY = "aksjdhkajsdhkasjhd"

if len(sys.argv) <= 1:
    print("[+] Usage: ./gnql yourqueryhere")
    sys.exit(1)

# Smash args together
query = " ".join(sys.argv[1:])

# Issue request against API
r = requests.get("https://research.api.greynoise.io/v2/experimental/gnql", params={"query": query}, headers={"key": GREYNOISE_API_KEY})

# Print the results
print(r.text.encode("utf-8"))
